##
## EPITECH PROJECT, 2022
## zggqhd
## File description:
## a
##

all:
		@make -C generator/
		@make -C solver/
clean:
		@make clean -C generator/
		@make clean -C solver/
fclean:
		@make fclean -C generator/
		@make fclean -C solver/
re:
		@make fclean -C generator/
		@make fclean -C solver/
		@make -C generator/
		@make -C solver/